package main

import (
	"flag"
	"fmt"
	"io/ioutil"
	"log"
	"os"
	"path"
	"strings"
	"time"

	"github.com/azavorotnii/slicemeta/internal/flagutil"
	"github.com/azavorotnii/slicemeta/internal/templates"
)

const version = "0.0.3a"

func main() {
	var (
		typeName    string
		imports     flagutil.StringList
		equalOp     string
		lessOp      string
		packageName string
		outputDir   string
		methods     string
	)

	flag.StringVar(&typeName, "type", "", "type name of slice element asa it is used in other packages (with package name prefix).")
	flag.Var(&imports, "import", "imports to be includes in generated package.")
	flag.StringVar(&equalOp, "equal", "operator",
		"can be 'operator', 'method', 'deep' or custom format string with 2 '%v' arguments.")
	flag.StringVar(&lessOp, "less", "",
		"to make sortable wrapper can be 'operator' or custom format string with 2 '%v' arguments.")
	flag.StringVar(&packageName, "package", "", "")
	flag.StringVar(&methods, "methods", "", "")
	flag.StringVar(&outputDir, "outputDir", "", "")
	flag.Parse()

	if typeName == "" {
		flag.Usage()
		log.Fatal("type is mandatory argument")
	}
	if packageName == "" {
		name := typeName[strings.LastIndex(typeName, ".")+1:]
		packageName = strings.ToLower(name) + "util"
	}

	if outputDir == "" {
		cwd, err := os.Getwd()
		if err != nil {
			log.Fatal(err)
		}
		outputDir = cwd
	}
	outputDir = path.Join(outputDir, packageName)
	if err := os.MkdirAll(outputDir, 0777); err != nil {
		log.Fatal(err)
	}

	config := templates.Config{
		PackageName: packageName,
		Imports:     imports,
		Comment:     fmt.Sprintf("Generated by %v-%v (%v)", path.Base(os.Args[0]), version, time.Now().Format(time.RFC3339)),
		TypeName:    typeName,

		MethodsRegex: methods,
	}

	switch equalOp {
	case "", "operator":
		templates.UseEqualOperator(&config)
	case "method":
		templates.UseEqualMethod(&config)
	case "deep":
		templates.UseDeepEqual(&config)
	default:
		// needs parenteses so "!equal" will work as well
		templates.UseEqualFormat(&config, "("+equalOp+")")
	}

	switch lessOp {
	case "":
		// by default no sortable wrapper
	case "operator":
		templates.UseLessOperator(&config)
	default:
		templates.UseLessFormat(&config, lessOp)
	}

	goCode, err := templates.FormatPackageCode(config)
	if err != nil {
		log.Fatalf("%v: %+v\n", packageName, err)
	}
	if err := ioutil.WriteFile(path.Join(outputDir, packageName+".go"), goCode, 0755); err != nil {
		log.Fatalf("%v: %+v\n", packageName, err)
	}
}
